INSERT INTO public.news (id, category_id, main_image_id, title, content, description, publication_time, created_at, updated_at) VALUES (2, 2, 2, 'News title 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam faucibus elementum sapien, commodo interdum neque volutpat a. Duis porttitor accumsan sollicitudin. Pellentesque euismod lectus mollis odio pretium gravida. Curabitur tempus diam sed nibh luctus, accumsan fringilla magna venenatis. Nullam sit amet congue ligula. Sed placerat vehicula mi, sit amet finibus libero rutrum quis. Etiam imperdiet, sapien id dapibus congue, dui purus volutpat ex, eget condimentum metus ex ut ante. Donec a tempor est, et tincidunt diam. Cras euismod gravida eros in semper. Maecenas erat tortor, euismod in consequat ac, porttitor a nulla. Nunc sollicitudin, nunc quis fringilla accumsan, lectus diam iaculis nunc, efficitur tempor mauris mauris at lacus. Integer sed faucibus risus. Nulla convallis sapien nec vestibulum eleifend. Nunc sed quam diam.

Sed dui orci, blandit mollis nibh at, rhoncus pellentesque dui. Donec vulputate magna at lacus aliquam molestie. Cras in sollicitudin augue. Aenean accumsan nisi vel est ullamcorper auctor. Quisque efficitur dignissim varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent quis urna sapien. Aenean consequat gravida urna, at commodo lorem pulvinar quis. Morbi at magna in mi scelerisque fringilla at non nunc. Integer a pharetra ligula. Etiam tellus libero, placerat eu viverra lacinia, tristique sed massa. Morbi tempus ornare lacus, nec tristique est rutrum non. Nam in sapien auctor, interdum dui vel, aliquet lacus. Curabitur placerat ultricies justo, vitae feugiat elit condimentum sed. Aenean tristique, augue in ultricies tempor, dui felis convallis odio, sed rutrum orci diam at lacus. Duis vel sem enim.

Sed a mollis dolor. Maecenas placerat ligula non mi ultricies tristique. Aliquam laoreet mauris nec vestibulum aliquet. Morbi nisi enim, pulvinar efficitur finibus sed, faucibus ut tortor. Mauris molestie elit nec ultrices tincidunt. Nunc facilisis velit mi, ut interdum turpis lobortis id. Nam odio enim, gravida sed ex vitae, blandit pretium mi. Nulla viverra risus eget gravida vestibulum. Nam ipsum ligula, tempus vel leo quis, molestie hendrerit nulla. Integer at purus nec lorem maximus hendrerit. Quisque nec rhoncus lectus, a efficitur leo. Sed sed urna nisi. Quisque in tellus blandit, semper turpis ac, vestibulum mi. Aliquam tempor auctor egestas.', 'Changed news description 2', '2019-08-18 22:55:07.475000', '2019-08-20 22:55:07.475645', '2019-08-20 22:55:07.475645');
INSERT INTO public.news (id, category_id, main_image_id, title, content, description, publication_time, created_at, updated_at) VALUES (3, 5, 3, 'News title 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam faucibus elementum sapien, commodo interdum neque volutpat a. Duis porttitor accumsan sollicitudin. Pellentesque euismod lectus mollis odio pretium gravida. Curabitur tempus diam sed nibh luctus, accumsan fringilla magna venenatis. Nullam sit amet congue ligula. Sed placerat vehicula mi, sit amet finibus libero rutrum quis. Etiam imperdiet, sapien id dapibus congue, dui purus volutpat ex, eget condimentum metus ex ut ante. Donec a tempor est, et tincidunt diam. Cras euismod gravida eros in semper. Maecenas erat tortor, euismod in consequat ac, porttitor a nulla. Nunc sollicitudin, nunc quis fringilla accumsan, lectus diam iaculis nunc, efficitur tempor mauris mauris at lacus. Integer sed faucibus risus. Nulla convallis sapien nec vestibulum eleifend. Nunc sed quam diam.

Sed dui orci, blandit mollis nibh at, rhoncus pellentesque dui. Donec vulputate magna at lacus aliquam molestie. Cras in sollicitudin augue. Aenean accumsan nisi vel est ullamcorper auctor. Quisque efficitur dignissim varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent quis urna sapien. Aenean consequat gravida urna, at commodo lorem pulvinar quis. Morbi at magna in mi scelerisque fringilla at non nunc. Integer a pharetra ligula. Etiam tellus libero, placerat eu viverra lacinia, tristique sed massa. Morbi tempus ornare lacus, nec tristique est rutrum non. Nam in sapien auctor, interdum dui vel, aliquet lacus. Curabitur placerat ultricies justo, vitae feugiat elit condimentum sed. Aenean tristique, augue in ultricies tempor, dui felis convallis odio, sed rutrum orci diam at lacus. Duis vel sem enim.

Sed a mollis dolor. Maecenas placerat ligula non mi ultricies tristique. Aliquam laoreet mauris nec vestibulum aliquet. Morbi nisi enim, pulvinar efficitur finibus sed, faucibus ut tortor. Mauris molestie elit nec ultrices tincidunt. Nunc facilisis velit mi, ut interdum turpis lobortis id. Nam odio enim, gravida sed ex vitae, blandit pretium mi. Nulla viverra risus eget gravida vestibulum. Nam ipsum ligula, tempus vel leo quis, molestie hendrerit nulla. Integer at purus nec lorem maximus hendrerit. Quisque nec rhoncus lectus, a efficitur leo. Sed sed urna nisi. Quisque in tellus blandit, semper turpis ac, vestibulum mi. Aliquam tempor auctor egestas.

Nullam sed ornare nibh, id iaculis dui. Mauris lobortis interdum dui, sed vestibulum sapien scelerisque accumsan. Aliquam tortor justo, finibus quis erat et, fermentum semper arcu. Nam tempus lectus eros, ut suscipit libero ultricies sit amet. Vestibulum in nibh et purus ornare consectetur id eget turpis. Nullam nec augue non diam volutpat pretium. Proin tincidunt nunc eget ante iaculis volutpat. Mauris id tincidunt justo. Nulla finibus accumsan massa, quis gravida mauris accumsan eu. Integer in vehicula elit.

Morbi finibus dui ac elit tempus, ut ultricies erat luctus. Cras imperdiet magna tellus, nec sodales lorem elementum ut. Cras eget fermentum lectus. Quisque eget tellus orci. Duis sed ornare arcu. Duis lacinia mauris justo, non suscipit neque consectetur vel. Proin sit amet maximus quam, id dictum diam.

Duis placerat tellus ut erat molestie, quis sodales nisi efficitur. Maecenas mollis ipsum purus, a rutrum ligula iaculis ut. Fusce consectetur vel tortor ac efficitur. Praesent dui turpis, cursus non tortor in, consequat dictum est. Mauris ultricies elementum tincidunt. Suspendisse elementum purus nec dolor placerat, nec tristique mi faucibus. Curabitur volutpat luctus ipsum vitae mattis. Proin et consequat odio, vel bibendum nibh. Etiam at suscipit orci, non varius augue. Nam quis arcu ac tellus posuere egestas in vitae odio. Suspendisse ac tincidunt dolor. In vehicula vestibulum orci, eu vestibulum risus mattis at. Duis id malesuada sapien.

Aenean congue tellus egestas turpis ullamcorper, volutpat malesuada elit rutrum. Quisque ac tincidunt tellus. Ut consectetur varius sodales. Sed dictum eget sem ac dapibus. Etiam id varius ex. Pellentesque sodales mollis diam eu venenatis. Donec elementum massa non porta suscipit. Nam condimentum odio vitae lacus lacinia ultrices. Sed egestas erat at libero pellentesque auctor. Mauris feugiat vitae urna eget porta. Suspendisse gravida et massa nec congue. Nam aliquam, lacus non tristique accumsan, odio ante convallis nunc, in lacinia odio lectus sit amet sapien. Sed vestibulum tincidunt nunc, non pharetra mauris pretium eu. Duis semper aliquam libero non bibendum.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis vel tortor vitae lorem posuere fringilla. Nunc ut nisi vel augue mollis viverra. Donec auctor enim et faucibus interdum. Nulla dui nisi, pellentesque sed vehicula sit amet, congue quis risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer ultrices tellus ac lacus pharetra dignissim. Nunc quis nulla urna. Cras commodo, nisl sed sodales venenatis, urna sapien faucibus ligula, nec eleifend elit sem sed eros. Integer ut odio mattis, molestie felis ac, tincidunt turpis. Donec sed risus convallis, convallis risus id, sollicitudin magna. Pellentesque nec nulla ut dui lobortis lobortis sit amet nec odio. Fusce non luctus metus. Quisque semper pretium lacinia.

Donec tristique quis diam ut commodo. Integer eleifend elit id leo ullamcorper ornare. Praesent sapien nulla, aliquam eu turpis iaculis, volutpat suscipit augue. Mauris eget tortor interdum elit aliquam aliquet. Etiam ut elit orci. Nullam eget eleifend ex. Proin facilisis elit quis eros rutrum, a condimentum diam efficitur. Phasellus ac diam neque. Ut ultrices sed metus id rhoncus. Curabitur quis semper risus. In vel nibh tempor, commodo tortor vel, fringilla mi. Integer imperdiet sit amet purus id malesuada.

Pellentesque pharetra et lorem elementum mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas sodales risus egestas, feugiat ipsum eget, varius nisl. Quisque gravida rhoncus neque sit amet malesuada. Sed egestas non est eu feugiat. Proin porttitor diam eu euismod dictum. Vivamus auctor mollis posuere.

Duis aliquam, ligula nec dignissim placerat, justo orci consequat tellus, nec posuere neque nunc sed nisl. Aenean pellentesque eget arcu in lobortis. Ut dapibus urna at magna porta, ut sodales erat lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras placerat nisi eu urna posuere, quis egestas tortor consequat. Phasellus tempor semper arcu tincidunt maximus. Sed tempor eros sed est malesuada, quis fermentum risus tristique. Phasellus pulvinar, lacus a sodales iaculis, elit diam laoreet sapien, eu volutpat ligula purus vitae lacus. In pretium mauris lectus, ac commodo purus tempus nec. Pellentesque sit amet augue fringilla, feugiat augue et, condimentum felis.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut malesuada urna. Praesent varius pharetra risus, quis volutpat est sagittis et. Praesent a magna sit amet nisi sollicitudin dictum. Nunc ut ante nec ipsum faucibus sollicitudin maximus in orci. Aenean et posuere neque. Cras sit amet egestas odio, in mollis quam. Proin ornare dolor tincidunt dolor ornare tristique.

Aliquam eleifend congue accumsan. Suspendisse dignissim non sem nec gravida. Cras at efficitur erat. Suspendisse tincidunt sem ut augue euismod, at fermentum lectus hendrerit. Integer consequat nec tellus eu ultrices. Aenean placerat ligula nec faucibus fringilla. Donec lacinia a turpis at efficitur. Duis varius nisi vel nulla egestas, id vulputate risus venenatis. In gravida pretium dolor in vehicula.

Nunc pretium augue a rutrum consectetur. Curabitur sed lorem eget leo dignissim semper et consequat massa. Sed congue justo finibus metus sagittis, vel mollis dui sodales. Cras id erat vel tellus placerat efficitur et ac ligula. Suspendisse convallis lectus non massa scelerisque mattis. Cras feugiat vitae ligula id dignissim. Quisque eros nulla, laoreet sed tempor ut, interdum quis mauris. Nullam at ipsum sit amet urna varius mattis nec id metus. Mauris at viverra velit. Phasellus gravida auctor diam, id hendrerit lectus iaculis vitae. Suspendisse sollicitudin porttitor ultrices. Duis luctus diam nunc, nec eleifend elit ultricies sed. Suspendisse ac ultricies arcu. Curabitur libero purus, dignissim in gravida vel, malesuada ut eros. Aliquam eget justo non libero efficitur mollis vel ac augue. Sed interdum mauris placerat lacus viverra ultrices nec eget nisi.

Phasellus sapien neque, fringilla a finibus at, elementum at orci. Integer at mollis massa. Aliquam nisl ante, ullamcorper eu leo in, feugiat condimentum nulla. Donec mattis ipsum nunc, vel dignissim ligula laoreet eget. Curabitur et dolor arcu. Vestibulum scelerisque lorem eu nulla vehicula, quis consequat ex scelerisque. Nulla et fringilla felis. Praesent risus turpis, semper eu orci interdum, egestas luctus leo. ', 'Morbi finibus dui ac elit tempus, ut ultricies erat luctus. Cras imperdiet magna tellus, nec sodales lorem elementum ut. Cras eget fermentum lectus. Quisque eget tellus orci. Duis sed ornare arcu. Duis lacinia mauris justo, non suscipit neque consectetur vel. Proin sit amet maximus quam, id dictum diam.', '2019-08-20 22:55:44.457197', '2019-08-20 22:55:44.457197', '2019-08-20 22:55:44.457197');
INSERT INTO public.news (id, category_id, main_image_id, title, content, description, publication_time, created_at, updated_at) VALUES (4, 1, 1, 'News Title 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam faucibus elementum sapien, commodo interdum neque volutpat a. Duis porttitor accumsan sollicitudin. Pellentesque euismod lectus mollis odio pretium gravida. Curabitur tempus diam sed nibh luctus, accumsan fringilla magna venenatis. Nullam sit amet congue ligula. Sed placerat vehicula mi, sit amet finibus libero rutrum quis. Etiam imperdiet, sapien id dapibus congue, dui purus volutpat ex, eget condimentum metus ex ut ante. Donec a tempor est, et tincidunt diam. Cras euismod gravida eros in semper. Maecenas erat tortor, euismod in consequat ac, porttitor a nulla. Nunc sollicitudin, nunc quis fringilla accumsan, lectus diam iaculis nunc, efficitur tempor mauris mauris at lacus. Integer sed faucibus risus. Nulla convallis sapien nec vestibulum eleifend. Nunc sed quam diam.

Sed dui orci, blandit mollis nibh at, rhoncus pellentesque dui. Donec vulputate magna at lacus aliquam molestie. Cras in sollicitudin augue. Aenean accumsan nisi vel est ullamcorper auctor. Quisque efficitur dignissim varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent quis urna sapien. Aenean consequat gravida urna, at commodo lorem pulvinar quis. Morbi at magna in mi scelerisque fringilla at non nunc. Integer a pharetra ligula. Etiam tellus libero, placerat eu viverra lacinia, tristique sed massa. Morbi tempus ornare lacus, nec tristique est rutrum non. Nam in sapien auctor, interdum dui vel, aliquet lacus. Curabitur placerat ultricies justo, vitae feugiat elit condimentum sed. Aenean tristique, augue in ultricies tempor, dui felis convallis odio, sed rutrum orci diam at lacus. Duis vel sem enim.

Sed a mollis dolor. Maecenas placerat ligula non mi ultricies tristique. Aliquam laoreet mauris nec vestibulum aliquet. Morbi nisi enim, pulvinar efficitur finibus sed, faucibus ut tortor. Mauris molestie elit nec ultrices tincidunt. Nunc facilisis velit mi, ut interdum turpis lobortis id. Nam odio enim, gravida sed ex vitae, blandit pretium mi. Nulla viverra risus eget gravida vestibulum. Nam ipsum ligula, tempus vel leo quis, molestie hendrerit nulla. Integer at purus nec lorem maximus hendrerit. Quisque nec rhoncus lectus, a efficitur leo. Sed sed urna nisi. Quisque in tellus blandit, semper turpis ac, vestibulum mi. Aliquam tempor auctor egestas.

Nullam sed ornare nibh, id iaculis dui. Mauris lobortis interdum dui, sed vestibulum sapien scelerisque accumsan. Aliquam tortor justo, finibus quis erat et, fermentum semper arcu. Nam tempus lectus eros, ut suscipit libero ultricies sit amet. Vestibulum in nibh et purus ornare consectetur id eget turpis. Nullam nec augue non diam volutpat pretium. Proin tincidunt nunc eget ante iaculis volutpat. Mauris id tincidunt justo. Nulla finibus accumsan massa, quis gravida mauris accumsan eu. Integer in vehicula elit.

Morbi finibus dui ac elit tempus, ut ultricies erat luctus. Cras imperdiet magna tellus, nec sodales lorem elementum ut. Cras eget fermentum lectus. Quisque eget tellus orci. Duis sed ornare arcu. Duis lacinia mauris justo, non suscipit neque consectetur vel. Proin sit amet maximus quam, id dictum diam.

Duis placerat tellus ut erat molestie, quis sodales nisi efficitur. Maecenas mollis ipsum purus, a rutrum ligula iaculis ut. Fusce consectetur vel tortor ac efficitur. Praesent dui turpis, cursus non tortor in, consequat dictum est. Mauris ultricies elementum tincidunt. Suspendisse elementum purus nec dolor placerat, nec tristique mi faucibus. Curabitur volutpat luctus ipsum vitae mattis. Proin et consequat odio, vel bibendum nibh. Etiam at suscipit orci, non varius augue. Nam quis arcu ac tellus posuere egestas in vitae odio. Suspendisse ac tincidunt dolor. In vehicula vestibulum orci, eu vestibulum risus mattis at. Duis id malesuada sapien.', 'Morbi finibus dui ac elit tempus, ut ultricies erat luctus. Cras imperdiet magna tellus, nec sodales lorem elementum ut. Cras eget fermentum lectus. Quisque eget tellus orci. Duis sed ornare arcu. Duis lacinia mauris justo, non suscipit neque consectetur vel. Proin sit amet maximus quam, id dictum diam.', '2019-09-01 22:54:08.172000', '2019-09-04 17:13:25.323000', '2019-09-04 17:37:42.467000');
INSERT INTO public.news (id, category_id, main_image_id, title, content, description, publication_time, created_at, updated_at) VALUES (1, 1, 1, 'Very first news title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam faucibus elementum sapien, commodo interdum neque volutpat a. Duis porttitor accumsan sollicitudin. Pellentesque euismod lectus mollis odio pretium gravida. Curabitur tempus diam sed nibh luctus, accumsan fringilla magna venenatis. Nullam sit amet congue ligula. Sed placerat vehicula mi, sit amet finibus libero rutrum quis. Etiam imperdiet, sapien id dapibus congue, dui purus volutpat ex, eget condimentum metus ex ut ante. Donec a tempor est, et tincidunt diam. Cras euismod gravida eros in semper. Maecenas erat tortor, euismod in consequat ac, porttitor a nulla. Nunc sollicitudin, nunc quis fringilla accumsan, lectus diam iaculis nunc, efficitur tempor mauris mauris at lacus. Integer sed faucibus risus. Nulla convallis sapien nec vestibulum eleifend. Nunc sed quam diam.

Sed dui orci, blandit mollis nibh at, rhoncus pellentesque dui. Donec vulputate magna at lacus aliquam molestie. Cras in sollicitudin augue. Aenean accumsan nisi vel est ullamcorper auctor. Quisque efficitur dignissim varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent quis urna sapien. Aenean consequat gravida urna, at commodo lorem pulvinar quis. Morbi at magna in mi scelerisque fringilla at non nunc. Integer a pharetra ligula. Etiam tellus libero, placerat eu viverra lacinia, tristique sed massa. Morbi tempus ornare lacus, nec tristique est rutrum non. Nam in sapien auctor, interdum dui vel, aliquet lacus. Curabitur placerat ultricies justo, vitae feugiat elit condimentum sed. Aenean tristique, augue in ultricies tempor, dui felis convallis odio, sed rutrum orci diam at lacus. Duis vel sem enim.

Sed a mollis dolor. Maecenas placerat ligula non mi ultricies tristique. Aliquam laoreet mauris nec vestibulum aliquet. Morbi nisi enim, pulvinar efficitur finibus sed, faucibus ut tortor. Mauris molestie elit nec ultrices tincidunt. Nunc facilisis velit mi, ut interdum turpis lobortis id. Nam odio enim, gravida sed ex vitae, blandit pretium mi. Nulla viverra risus eget gravida vestibulum. Nam ipsum ligula, tempus vel leo quis, molestie hendrerit nulla. Integer at purus nec lorem maximus hendrerit. Quisque nec rhoncus lectus, a efficitur leo. Sed sed urna nisi. Quisque in tellus blandit, semper turpis ac, vestibulum mi. Aliquam tempor auctor egestas.

Nullam sed ornare nibh, id iaculis dui. Mauris lobortis interdum dui, sed vestibulum sapien scelerisque accumsan. Aliquam tortor justo, finibus quis erat et, fermentum semper arcu. Nam tempus lectus eros, ut suscipit libero ultricies sit amet. Vestibulum in nibh et purus ornare consectetur id eget turpis. Nullam nec augue non diam volutpat pretium. Proin tincidunt nunc eget ante iaculis volutpat. Mauris id tincidunt justo. Nulla finibus accumsan massa, quis gravida mauris accumsan eu. Integer in vehicula elit.

Morbi finibus dui ac elit tempus, ut ultricies erat luctus. Cras imperdiet magna tellus, nec sodales lorem elementum ut. Cras eget fermentum lectus. Quisque eget tellus orci. Duis sed ornare arcu. Duis lacinia mauris justo, non suscipit neque consectetur vel. Proin sit amet maximus quam, id dictum diam.

Duis placerat tellus ut erat molestie, quis sodales nisi efficitur. Maecenas mollis ipsum purus, a rutrum ligula iaculis ut. Fusce consectetur vel tortor ac efficitur. Praesent dui turpis, cursus non tortor in, consequat dictum est. Mauris ultricies elementum tincidunt. Suspendisse elementum purus nec dolor placerat, nec tristique mi faucibus. Curabitur volutpat luctus ipsum vitae mattis. Proin et consequat odio, vel bibendum nibh. Etiam at suscipit orci, non varius augue. Nam quis arcu ac tellus posuere egestas in vitae odio. Suspendisse ac tincidunt dolor. In vehicula vestibulum orci, eu vestibulum risus mattis at. Duis id malesuada sapien.', 'Morbi finibus dui ac elit tempus, ut ultricies erat luctus. Cras imperdiet magna tellus, nec sodales lorem elementum ut. Cras eget fermentum lectus. Quisque eget tellus orci. Duis sed ornare arcu. Duis lacinia mauris justo, non suscipit neque consectetur vel. Proin sit amet maximus quam, id dictum diam.', '2019-08-15 22:54:08.017000', '2019-08-20 22:54:08.172929', '2019-09-04 19:37:10.754000');
INSERT INTO public.news (id, category_id, main_image_id, title, content, description, publication_time, created_at, updated_at) VALUES (5, 1, 1, 'News Title 5', 'It you see this news, that mean that is work !', 'Test from admin website', '2019-09-05 00:00:00.000000', '2019-09-04 18:09:28.256000', '2019-09-07 16:49:34.781000');